[package]
name = "computerdicuss_forum_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
poise = "0.5.5"
serde = "1.0.185"
toml = "0.7.6"
